# Generated by Django 4.1.2 on 2022-10-20 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('thumb', models.ImageField(upload_to='thumb-places')),
                ('category', models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('ATTRACTIONS', 'Attractions'), ('PARTYS', 'Partys'), ('OTHER', 'Other')], max_length=15)),
                ('adress', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
