# Generated by Django 4.1.2 on 2022-10-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_alter_place_category_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='average_rating',
            field=models.IntegerField(default=0),
        ),
    ]
